> * 广告位
> * 一起刷题群：
> * 添加微信heywhaleshequ，备注“学习”，带你认识更多一起刷题的小伙伴~

hi，大家好，X题系列又与大家见面了~这次是scikit-learn库。scikit-learn 是基于 Python 语言的机器学习工具简单高效的数据挖掘和数据分析工具。和pandas，numpy共称机器学习3巨头（又是我自己想的）
萌新可以参考以下教程：
- [Python机器学习笔记：sklearn库的学习](https://www.cnblogs.com/wj-1314/p/10179741.html)
- [scikit-learn (sklearn) 官方文档中文版](https://sklearn.apachecn.org/)
- [scikit-learn Machine Learning in Python](https://scikit-learn.org/stable/index.html)

------
其他x题系列：
* [50道练习带你玩转Pandas](https://www.kesci.com/home/project/5ddc974ef41512002cec1dca)
* [这100道练习，带你玩转Numpy](https://www.kesci.com/home/project/59f29f67c5f3f5119527a2cc)
* [35题初探scikit-learn库，get机器学习好帮手√ ](https://www.kesci.com/home/project/5df746242823a10036ac5532)
* [50题matplotlib从入门到精通](https://www.kesci.com/home/project/5de9f0a0953ca8002c95d2a9)
* [40题刷爆Keras，人生苦短我选Keras](https://www.kesci.com/home/project/5e1c14582823a10036b474de)
* [60题PyTorch简易入门指南，做技术的弄潮儿](https://www.kesci.com/home/project/5e0038642823a10036ae9ebf)
* [90题细品吴恩达《机器学习》，感受被刷题支配的恐惧](https://www.kesci.com/home/project/5e0f01282823a10036b280a7)
* [170题吴恩达《深度学习》面面观，一套更比三套强](https://www.kesci.com/home/project/5e20243e2823a10036b542da)

## 一、获取数据

1.导入sklearn的数据集模块
2.导入预置的手写数字数据集
3.生成数据用于聚类，100个样本，2个特征，5个类

In [2]:
from sklearn import datasets


In [8]:
import matplotlib.pyplot as plt

digits = datasets.load_digits()

plt.matshow(digits.images[0])
plt.show()


<Figure size 288x288 with 1 Axes>

In [9]:
data, label = datasets.make_blobs(n_samples=100, n_features=2, centers=5)

plt.scatter(data[:, 0], data[:, 1], c=label)
plt.show()


<Figure size 432x288 with 1 Axes>

## 二、数据预处理

4.导入sklearn的预处理模块
5.计算一组数据的平均值和标准差（scaler）
6.使用上一题的scaler标准化现有数据
7.用最小最大规范化对数据进行线性变换，变换到[0,1]区间
8.用L2正则化对数据进行变换
9.对现有数据进行one-hot编码
10.给定阈值，将特征转换为0/1
11.对现有数据进行标签编码

In [10]:
from sklearn import preprocessing

In [11]:
data = [[0, 0], [1, 0], [-1, 1], [1, 2]]

scalerstd = preprocessing.StandardScaler().fit(data)

print(scalerstd.mean_)
print(scalerstd.var_)

[0.25 0.75]
[0.6875 0.6875]


In [12]:
scalerstd.transform(data)

array([[-0.30151134, -0.90453403],
       [ 0.90453403, -0.90453403],
       [-1.50755672,  0.30151134],
       [ 0.90453403,  1.50755672]])

In [13]:
scalermm = preprocessing.MinMaxScaler(feature_range=(0, 1)).fit(data)
scalermm.transform(data)

array([[0.5, 0. ],
       [1. , 0. ],
       [0. , 0.5],
       [1. , 1. ]])

In [14]:
X = [[ 1., -1.,  2.],
    [ 2.,  0.,  0.],
    [ 0.,  1., -1.]]
    
scalernorm = preprocessing.Normalizer(norm='l2').fit(X)
scalernorm.transform(X)

# 方法二
# preprocessing.normalize(X, norm='l2')

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [15]:
data = [[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]]

scaleronehot = preprocessing.OneHotEncoder().fit(data)
scaleronehot.transform(data).toarray()

/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:414: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 0.]])

In [16]:
data = [[0, 0], [1, 0], [-1, 1], [1, 2]]

scalerbin = preprocessing.Binarizer(threshold=0.5)
scalerbin.transform(data)

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [ ]:
scalerlabel = preprocessing.LabelEncoder()
scalerlabel.fit(["paris", "paris", "tokyo", "amsterdam"])
scalerlabel.transform(["tokyo", "tokyo", "paris"])

array([2, 2, 1])

## 三、数据及拆分
12.将现有数据划分为训练集和测试集，测试集数量占比为30%
13.将现有数据划分为3折

In [25]:
from sklearn import model_selection

dataset = datasets.load_boston()
print(dataset.data.shape)

X_train, X_test, y_train, y_test = model_selection.train_test_split(
    dataset['data'], dataset['target'], test_size=0.3)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)


(506, 13)
(354, 13)
(152, 13)
(354,)
(152,)


In [26]:
import numpy as np
X = np.array(['a', 'b', 'c', 'd','e','f'])

kfold = model_selection.KFold(n_splits=3)

for train, test in kfold.split(X):
    print("%s %s" % (X[train], X[test]))

['c' 'd' 'e' 'f'] ['a' 'b']
['a' 'b' 'e' 'f'] ['c' 'd']
['a' 'b' 'c' 'd'] ['e' 'f']


## 四、使用模型
14.定义一个线性回归模型
15.导入预置的波士顿房价数据集
16.设置房价为Y，剩余参数为X，30%为测试集
17.用线性回归模型拟合波士顿房价数据集
18.用训练完的模型进行预测
19.输出线性回归模型的斜率和截距


In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression(fit_intercept=True, normalize=False,
    copy_X=True, n_jobs=1)

In [28]:
X, y = datasets.load_boston(return_X_y=True)


In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [30]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [31]:
model.predict(X_test)

array([28.2861349 , 21.97560216, 21.91396131, 17.79431563, 17.06565527,
       17.88854703, 13.32697214, 22.1430695 , 24.11795707, 24.39244761,
       18.33456366, 19.0916596 , 18.12400962, 27.42456278, 32.27619444,
        8.9413692 , 20.85851133, 26.12945766, 26.11177871, 34.10620276,
       28.46102619, 14.29751459, 30.78675881, 34.60712927, 40.50546095,
       19.43019268, 28.67716669, 19.28403905, 24.06282143, 21.4663773 ,
       19.92643428, 26.32460661, 30.48727147, 16.38006562, 22.8992174 ,
       21.66491234, 22.8583225 , 24.66460812, 24.05627551, 32.92751187,
       16.59580245, 24.20571714, 13.06968798, 10.12169996, 19.25023605,
       13.80439781, 28.37128812, 23.19515569, 28.1496853 , 16.7565839 ,
       36.59516841, 18.32664858, 22.07362558, 39.08542464, 23.0020432 ,
       24.53165645, 13.70908525, 28.7227526 , 10.15620126, 20.94556801,
       25.28486367, 15.18816835, 32.85127618, 34.95900053, 15.71030903,
       20.17785494, 24.78046017,  3.40209348, 22.0972941 , 30.28

In [32]:
print(model.coef_)
print(model.intercept_)


[-9.61858840e-02  4.25713106e-02  6.59295703e-03  1.20278633e+00
 -1.81068119e+01  3.98380783e+00  1.43664279e-02 -1.31353390e+00
  3.17850698e-01 -1.20745389e-02 -9.25809265e-01  1.05129985e-02
 -5.16041905e-01]
32.85364196470156


## 五、评估
20.使用随机森林对鸢尾花数据集进行预测，`n_estimators=100`
21.给产生的随机森林模型打分
22.输出模型的recision_score、recall_score、f1_score

In [4]:
from sklearn.ensemble import RandomForestClassifier
X,y = datasets.load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
y_pred

NameError: name 'train_test_split' is not defined

In [37]:
clf.score(X,y)

0.9866666666666667

In [39]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.92      0.92      0.92        13
           2       0.91      0.91      0.91        11

    accuracy                           0.96        45
   macro avg       0.94      0.94      0.94        45
weighted avg       0.96      0.96      0.96        45



23.使用手写数字数据集，随机森林算法进行分类，画出学习曲线
24.使用手写数字数据集，随机森林算法进行分类，参数n_estimators选择范围为`[10,20,40,80,160,250]`，画出验证曲线

In [5]:
from sklearn.model_selection import learning_curve

X,y = datasets.load_digits(return_X_y=True)

train_sizes,train_score,test_score = learning_curve(RandomForestClassifier(n_estimators = 10),X,y,train_sizes=[0.1,0.2,0.4,0.6,0.8,1],scoring='accuracy')

train_error =  1- np.mean(train_score,axis=1)
test_error = 1- np.mean(test_score,axis=1)

plt.plot(train_sizes,train_error,'o-',color = 'r',label = 'training')
plt.plot(train_sizes,test_error,'o-',color = 'g',label = 'testing')
plt.legend(loc='best')
plt.xlabel('traing examples')
plt.ylabel('error')
plt.show()


/opt/conda/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


NameError: name 'plt' is not defined

In [43]:
from sklearn.model_selection import validation_curve

X,y = datasets.load_digits(return_X_y=True)
param_range = [10,20,40,80,160,250]

train_score,test_score = validation_curve(RandomForestClassifier(),X,y,param_name='n_estimators',param_range=param_range,cv=10,scoring='accuracy')

train_score =  np.mean(train_score,axis=1)
test_score = np.mean(test_score,axis=1)

plt.plot(param_range,train_score,'o-',color = 'r',label = 'training')
plt.plot(param_range,test_score,'o-',color = 'g',label = 'testing')
plt.legend(loc='best')
plt.xlabel('number of tree')
plt.ylabel('accuracy')
plt.show()


<Figure size 432x288 with 1 Axes>

25.使用网格搜索，得手写数字数据集+随机森林算法的最优参数

In [44]:
from sklearn.model_selection import GridSearchCV
X,y = datasets.load_digits(return_X_y=True)
# 随机森林的参数
tree_param_grid={'min_samples_split':[3,6,9],'n_estimators':[10,50,100]}
grid=GridSearchCV(RandomForestClassifier(),param_grid=tree_param_grid,cv=5)
grid.fit(X,y)
grid.best_estimator_,grid.best_score_,grid.best_params_

(RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                        max_depth=None, max_features='auto', max_leaf_nodes=None,
                        min_impurity_decrease=0.0, min_impurity_split=None,
                        min_samples_leaf=1, min_samples_split=3,
                        min_weight_fraction_leaf=0.0, n_estimators=100,
                        n_jobs=None, oob_score=False, random_state=None,
                        verbose=0, warm_start=False),
 0.9404563160823595,
 {'min_samples_split': 3, 'n_estimators': 100})

26.取鸢尾花数据集中，类型=0,1的数据，变成一个二分类问题，使用线性内核的SVM进行拟合
27.计算出对应的ROC曲线
28.计算出对应的AUC

In [58]:
from sklearn import svm
X,y = datasets.load_iris(return_X_y=True)
X, y = X[y != 2], y[y != 2]

# 加一些噪音，不然模型太准了
random_state = np.random.RandomState(0)
n_samples, n_features = X.shape
X = np.c_[X, random_state.randn(n_samples, 200 * n_features)]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3,random_state=0)

svm = svm.SVC(kernel='linear', probability=True)

svm.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=True, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [59]:
from sklearn.metrics import roc_curve, auc

y_score = svm.decision_function(X_test)

fpr,tpr,threshold = roc_curve(y_test, y_score)

plt.plot(fpr, tpr, color='darkorange')
plt.plot([0, 1], [0, 1], color='navy', linestyle='--')

<Figure size 432x288 with 1 Axes>

In [61]:
roc_auc = auc(fpr,tpr) 
roc_auc

0.8133333333333334

## 六、降维

29.生成一组数据，10000个样本，3个特征，4个簇
30.对数据进行pca同纬度数量的投影，展示投影后的三个维度的分布
31.将3维数据降到2维
32.指定降维后主成分方差的比例（99%）进行降维
33.使用MLE算法，自动选择降维维度

In [73]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA

X, y = datasets.make_blobs(n_samples=10000, n_features=3, centers=[[3,3, 3], [0,0,0], [1,1,1], [2,2,2]], cluster_std=[0.2, 0.1, 0.2, 0.2], 
                  random_state =9)

fig = plt.figure()
ax = Axes3D(fig, rect=[0, 0, 1, 1], elev=30, azim=20)
plt.scatter(X[:, 0], X[:, 1], X[:, 2],marker='o')

/opt/conda/lib/python3.6/site-packages/matplotlib/collections.py:857: RuntimeWarning: invalid value encountered in sqrt
  scale = np.sqrt(self._sizes) * dpi / 72.0 * self._factor


<Figure size 432x288 with 1 Axes>

In [74]:
pca = PCA(n_components=3)
pca.fit(X)
print (pca.explained_variance_ratio_)
print (pca.explained_variance_)


[0.98318212 0.00850037 0.00831751]
[3.78521638 0.03272613 0.03202212]


In [76]:
pca = PCA(n_components=2)
pca.fit(X)
print (pca.explained_variance_ratio_)
print (pca.explained_variance_)

X_new = pca.transform(X)
plt.scatter(X_new[:, 0], X_new[:, 1],marker='o')
plt.show()

[0.98318212 0.00850037]
[3.78521638 0.03272613]


<Figure size 432x288 with 1 Axes>

In [61]:
pca = PCA(n_components=0.99)
pca.fit(X)
print (pca.explained_variance_ratio_)
print (pca.explained_variance_)
print (pca.n_components_)

[0.98318212 0.00850037]
[3.78521638 0.03272613]
2


In [62]:
pca = PCA(n_components='mle')
pca.fit(X)
print (pca.explained_variance_ratio_)
print (pca.explained_variance_)
print (pca.n_components_)

[0.98318212]
[3.78521638]
1


34.生成一组数据，10000个样本，3个特征，4个类别
35.对数据进行LDA降维

In [82]:
X2, y2 = datasets.make_classification(n_samples=1000, n_features=3, n_redundant=0, n_classes=3, n_informative=2,
                           n_clusters_per_class=1,class_sep =0.5, random_state =10)
fig = plt.figure()
ax = Axes3D(fig, rect=[0, 0, 1, 1], elev=30, azim=20)
ax.scatter(X2[:, 0], X2[:, 1], X2[:, 2],marker='o',c=y2)

<Figure size 432x288 with 1 Axes>

In [83]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components=2)
lda.fit(X2,y)
X2_new = lda.transform(X)
plt.scatter(X2_new[:, 0], X2_new[:, 1],marker='o',c=y2)
plt.show()

<Figure size 432x288 with 1 Axes>